### ISSUE TITLE
Flash or reboot causes Funhouse to go offline

### ISSUE THREAD

**Issue by kbmetz** [jwillikers/esphome-funhouse#1]
This isn't really related directly to the code or yaml. Just a question about the hardware. I cannot flash mine via USB or OTA once it's flashed with ESPhome. I have to flash a generic tasmota via the Tasmota web flasher, and then from the Tasmota OTA upgrade, then I can flash the esphome firmware. Wondering if there's any solution. Thanks

**Comment by jwillikers** [comment]
I don't think I've run into any issues flashing it except for having to hold down that very small button on the back when connecting the USB. For some reason, I don't think the board resets after being flashed, requiring it to be manually rebooted. I noticed a message about this in the output from `esptool`.

**Comment by kbmetz** [comment]
Yes, if order to flash mine I have to hold down the button in the back and then press the reset button. But then I can only flash it using tasmota. If I try and flash esphome OTA I can see the funhouse board reset (from the LCD) but then the OTA times out. Also the esphome web flasher doesn't work at all (even after holding the button in the back). I'll give esptool from the command line a try. Can you show me how you flash it using esptool from the command line? Thanks!

**Comment by kbmetz** [comment]
Solved it for flashing via the web (specifically home assistant). Added the following to the ota section
ota:
  safe_mode: false

Now I'm able to flash ota without issue. Hopefully this helps anyone else searching through github looking for funhouse stuff! Thanks!!

**Comment by jwillikers** [comment]
Oh, that's great! I'll have to add that to my file here. I wasn't aware of that option. I appreciate you following up on that!

**Comment by kbmetz** [comment]
When poking around and found it on the esphome site, I didn't know about it either! The dotstar LED's are working in ESPhome but I can't figure out how to make the speaker work or the ambient light detector. Happy to share my current config if you want.
